name: My Jobs

on:
  push:
    branches:
      - main

jobs:

  build_image:
    runs-on: [self-hosted, some-label]
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t myapp:lastest -f CICD-DockerRunner.API/Dockerfile .
      - name: Stop the Container
        run: docker stop myappContainer
      - name: Remove the Container
        run: docker rm myappContainer
      - name: Run Docker container
        run: docker run -d -p 4000:8080 --name myappContainer myapp:lastest
